"""Pydantic models for the application."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DocumentRequest(BaseModel):
    """Request model for document generation."""

    request: str = Field(..., description="Natural language request for document")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None, description="Optional metadata"
    )


class Task(BaseModel):
    """A single task in the execution plan."""

    id: int
    description: str
    dependencies: List[int] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """Execution plan generated by the Planner Agent."""

    document_type: str
    assumptions: Dict[str, str]
    tasks: List[Task]
    outline: List[str]


class DocumentSection(BaseModel):
    """A section of the document."""

    title: str
    content: str
    heading_level: int = 1


class DocumentStructure(BaseModel):
    """Complete document structure in JSON."""

    title: str
    sections: List[DocumentSection]


class SectionFeedback(BaseModel):
    """Feedback for a specific section."""

    section_title: str
    issues: List[str] = Field(default_factory=list)
    feedback: str


class ReviewFeedback(BaseModel):
    """Review feedback from the Reviewer Agent."""

    has_issues: bool
    grammar_issues: List[str] = Field(default_factory=list)
    consistency_issues: List[str] = Field(default_factory=list)
    structure_issues: List[str] = Field(default_factory=list)
    tone_issues: List[str] = Field(default_factory=list)
    section_feedback: List[SectionFeedback] = Field(default_factory=list)
    corrections: str = ""


class QualityScore(BaseModel):
    """Quality metrics for the generated document."""

    relevance: int = Field(..., ge=1, le=5)
    completeness: int = Field(..., ge=1, le=5)
    coherence: int = Field(..., ge=1, le=5)
    structure: int = Field(..., ge=1, le=5)
    overall: int = Field(..., ge=1, le=5)


class LLMMetrics(BaseModel):
    """Metrics from LLM calls."""

    model: str
    latency_ms: float
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class PipelineMetrics(BaseModel):
    """Pipeline execution metrics."""

    planner_latency_ms: float
    writer_latency_ms: float
    reviewer_latency_ms: float
    docx_generation_latency_ms: float
    total_execution_time_ms: float
    num_generated_tasks: int
    review_iterations: int
    llm_calls: List[LLMMetrics] = Field(default_factory=list)


class DocumentResponse(BaseModel):
    """Response model for document generation."""

    success: bool
    document_filename: str
    execution_plan: ExecutionPlan
    assumptions: Dict[str, str]
    metrics: PipelineMetrics
    quality_scores: Optional[QualityScore] = None
    message: str = ""
