"""Pydantic models for the application."""

from typing import Any, Dict, List, Optional
from datetime import datetime, date
from pydantic import BaseModel, Field


class DocumentRequest(BaseModel):
    """Request model for document generation."""

    request: str = Field(..., description="Natural language request for document")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None, description="Optional metadata"
    )


class Task(BaseModel):
    """A single task in the execution plan."""

    id: int
    description: str
    dependencies: List[int] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """Execution plan generated by the Planner Agent."""

    document_type: str
    assumptions: Dict[str, str]
    tasks: List[Task]
    outline: List[str]


class DocumentSection(BaseModel):
    """A section of the document."""

    title: str
    content: str
    heading_level: int = 1


class DocumentStructure(BaseModel):
    """Complete document structure in JSON."""

    title: str
    sections: List[DocumentSection]


class SectionFeedback(BaseModel):
    """Feedback for a specific section."""

    section_title: str
    issues: List[str] = Field(default_factory=list)
    feedback: str


class ReviewFeedback(BaseModel):
    """Review feedback from the Reviewer Agent."""

    has_issues: bool
    grammar_issues: List[str] = Field(default_factory=list)
    consistency_issues: List[str] = Field(default_factory=list)
    structure_issues: List[str] = Field(default_factory=list)
    tone_issues: List[str] = Field(default_factory=list)
    section_feedback: List[SectionFeedback] = Field(default_factory=list)
    corrections: str = ""


class QualityScore(BaseModel):
    """Quality metrics for the generated document."""

    relevance: int = Field(..., ge=1, le=5)
    completeness: int = Field(..., ge=1, le=5)
    coherence: int = Field(..., ge=1, le=5)
    structure: int = Field(..., ge=1, le=5)
    overall: int = Field(..., ge=1, le=5)


class LLMMetrics(BaseModel):
    """Metrics from LLM calls."""

    model: str
    latency_ms: float
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class PipelineMetrics(BaseModel):
    """Pipeline execution metrics."""

    planner_latency_ms: float
    writer_latency_ms: float
    reviewer_latency_ms: float
    docx_generation_latency_ms: float
    total_execution_time_ms: float
    num_generated_tasks: int
    review_iterations: int
    llm_calls: List[LLMMetrics] = Field(default_factory=list)


class DocumentResponse(BaseModel):
    """Response model for document generation."""

    success: bool
    document_filename: str
    execution_plan: ExecutionPlan
    assumptions: Dict[str, str]
    metrics: PipelineMetrics
    quality_scores: Optional[QualityScore] = None
    message: str = ""


# Student State & Progress Models

class TopicProgress(BaseModel):
    """Progress on a single topic."""

    topic_name: str
    completed_date: Optional[date] = None
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    hours_spent: float = 0.0
    revision_count: int = 0
    last_revised_date: Optional[date] = None


class StudentState(BaseModel):
    """Complete student progress state."""

    student_id: str
    created_date: date
    exam_deadline: Optional[date] = None
    learned_topics: List[TopicProgress] = Field(default_factory=list)
    available_hours_per_day: float = 6.0
    learning_velocity: float = 0.5
    last_updated: datetime = Field(default_factory=datetime.now)
    timezone: str = "UTC"

    def get_learned_topic_names(self) -> set:
        """Get names of all learned topics (confidence > 0.5)."""
        return {t.topic_name for t in self.learned_topics if t.confidence > 0.5}

    def get_unlearned_topic_names(self) -> set:
        """Get names of topics not yet learned."""
        return {t.topic_name for t in self.learned_topics if t.confidence <= 0.5}

    def get_days_until_exam(self) -> Optional[int]:
        """Days remaining until exam deadline."""
        if not self.exam_deadline:
            return None
        today = date.today()
        return (self.exam_deadline - today).days

    def get_remaining_topics(self, total_curriculum_topics: int) -> int:
        """Estimate remaining topics to learn."""
        learned_count = len(self.get_learned_topic_names())
        return max(0, total_curriculum_topics - learned_count)


class ProgressClaim(BaseModel):
    """Extracted progress claim from user input."""

    claim_type: str
    topic_name: Optional[str] = None
    completion_date: Optional[date] = None
    hours: Optional[float] = None
    confidence: Optional[float] = None
    extracted_text: str


class ProgressUpdate(BaseModel):
    """Update to apply to student state."""

    student_id: str
    claims: List[ProgressClaim]
    updated_state: StudentState
    extraction_confidence: float = 0.8


class StudyPlan(BaseModel):
    """Generated study plan with validation metadata."""

    student_id: str
    generated_date: datetime = Field(default_factory=datetime.now)
    scope: str
    topics: List[str]
    daily_load: float
    total_hours: float
    is_feasible: bool
    validation_issues: List[str] = Field(default_factory=list)
    confidence_score: float = Field(0.0, ge=0.0, le=1.0)


# Chat Models

class ChatMessage(BaseModel):
    """A single message in the chat conversation."""

    role: str  # "user", "assistant", or "system"
    content: str
    timestamp: datetime = Field(default_factory=datetime.now)


class ClarifyingQuestion(BaseModel):
    """A clarifying question for the user."""

    question: str
    key: str  # e.g., "audience", "scope", "tone"
    options: Optional[List[str]] = None  # Multiple choice options
    required: bool = True


class ChatContext(BaseModel):
    """Context accumulated during chat conversation."""

    initial_request: str
    conversation: List[ChatMessage] = Field(default_factory=list)
    answers: Dict[str, str] = Field(default_factory=dict)  # question_key -> answer
    is_ready_to_generate: bool = False
    confidence_level: float = 0.0  # How confident we are to generate


class ChatResponse(BaseModel):
    """Response from chat endpoint."""

    message: str
    session_id: Optional[str] = None  # Set by API endpoint
    questions: Optional[List[ClarifyingQuestion]] = None
    context: ChatContext
    is_ready_to_generate: bool
    next_action: str  # "ask_more", "ready_to_generate", "generate_now"


class GenerateFromChatRequest(BaseModel):
    """Request to generate document from chat context."""

    session_id: str
    context: ChatContext
